### ISSUE TITLE
Error in .fileCopy

### ISSUE THREAD

**Issue by aropski** [fisabio/pbugs#5]
Hello

I'm receiving the following error when attempting to run the example from the help documentation:

`Error in .fileCopy(bugs.directory, pbugs.directory, recursive = TRUE,  : 
  attempt to copy a directory to itself`

I am running R as an admin but also define the location of WinBugs, which is not on the C-drive:

`result    <- pbugs(	data = bugs_data, 
					inits = bugs_init, 
					parameters.to.save = bugs_pars,
					model.file = bugs_model, 
					n.thin = 1, 
					n.chains = 2, 
					bugs.directory = 'E:/WinBUGS14/', 
					pbugs.directory = 'E:/WinBUGS14/', 
					debug=TRUE)`

If I remove pbugs.directory argument, then WinBugs does open, but displays "incompatible copy" and the following is displayed in R:

`Error in bugs.sims(parameters.to.save = parameters.to.save, n.chains = n.chains,  : 
  No chain ran properly.
In addition: Warning messages:
1: Chain 1 did not run correctly.
 Look at the log file and try again with 'debug=TRUE' to
 figure out what went wrong within Bugs. 
2: Chain 2 did not run correctly.
 Look at the log file and try again with 'debug=TRUE' to
 figure out what went wrong within Bugs. 
3: Chains without errors: 0 of 2 `

Can you please provide any assistance in resolving? Here is the sessionInfo.
Best,

`
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

Random number generation:
 RNG:     L'Ecuyer-CMRG 
 Normal:  Inversion 
 Sample:  Rejection 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pbugs_1.0.3

loaded via a namespace (and not attached):
[1] compiler_4.0.3 parallel_4.0.3 tools_4.0.3  `

**Comment by aropski** [comment]
I was able to successfully run a different example without issue.

**Comment by carlosvergara** [comment]
Hi,
OK. In any case, the problem arises when using the same directory in the arguments `bugs.directory` and `pbugs.directory`: if you use different directories you shouldn't get any error.
Best! :)
