### ISSUE TITLE
pbugs cannot be used under R 4.3

### ISSUE THREAD

**Issue by qqian-biostat** [fisabio/pbugs#6]
Recently, after I upgraded my R software, I have found a problem using 'pbugs'. It shows: package ‘pbugs’ is not available for this version of R (R 4.3). Is there some methods regarding this? Thank you.

**Comment by carlosvergara** [comment]
Hi,

What OS do you use? I don't see any problem neither on Linux nor on Windows (checked with `rhub`), and the check with `devtools::check_mac_release()` doesn't return any issue.

Are you trying to install it with `install.packages("pbugs")` or with `remotes::install_github("fisabio/pbugs")`? Note that the package is not available on CRAN: only on GitHub.

Thanks for using `pbugs`! :)
