### ISSUE TITLE
Data not found on R 4.4.0

### ISSUE THREAD

**Issue by sachijay** [fisabio/pbugs#9]
Gives an error from all clusters saying the data object was not found. The same code runs fine on R 4.3.3 and when using `R2WinBUGS` on R 4.4.0.

**Comment by carlosvergara** [comment]
Hi,

Yes, a few months ago I added a new argument to the `pbugs` function to solve this issue: in my case the object with the data was not found when using any of its elements in the generation of initial values..

Update the package, try using the new argument `cluster_export = c("your_data_to_export")` and let me know if the problem persists (if so, I would need a reproducible example and info from your session: R version and your OS).

:)
